### ISSUE TITLE
help

### ISSUE THREAD

**Issue by MonaDone1** [JannoEsko/q3panel#3]
hi, 
when i go to step3 i do "No" But it takes me to login page

**Comment by JannoEsko** [comment]
Hi, can you delete config.php file and try again? By browsing the source code I do not see a reason why it shouldn't go into step 4. Also worth noting that the project is dead and hasn't been kept up to date.

**Comment by MonaDone1** [comment]
I did a lot But same problem

**Comment by MonaDone1** [comment]
ok i fix it now ty

**Comment by MonaDone1** [comment]
hello,
when i do host it's show me this "Something went wrong with your action, please, check the data you provided (if any), try again or refresh the page and try again.
"

**Comment by JannoEsko** [comment]
Please add more information, like screenshots, output from JS console / AJAX request request + response

**Comment by MonaDone1** [comment]
![bandicam 2023-02-15 23-11-34-663](https://user-images.githubusercontent.com/112666939/219165013-f95115f7-4b62-47d0-a1b4-d954d1e71ff6.jpg)

**Comment by JannoEsko** [comment]
Only reason you end up to this command is bad setup / incorrect password or not having root logins permitted etc. from the source of the panel itself, the only command what is fired after getting the data is ‘whoami’ which should exist in most if not all Linux distros . If you’re trying to do this on a windows server, then you’re out of luck as windows compatibility, while planned, was never built.

therefore item closed.
