### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Testol113** [JannoEsko/q3panel#4]
Hello 
Why i can't see all folder FTP?

![bandicam 2023-02-18 02-01-44-172](https://user-images.githubusercontent.com/125708276/219818904-7b2e1b80-fdf0-4f41-8db6-035d2a59add4.jpg)

**Comment by JannoEsko** [comment]
Please include logs. Also check whether you have an ftp server installed.

**Comment by Testol113** [comment]
i have already but i can't too login with ftp

**Comment by JannoEsko** [comment]
Can you connect to the ftp with a regular ftp client? If not then it’s not a panel issue at all.

before reopening / creating a new issue, please include logs, as otherwise I’m just in the dark and cannot unfortunately support
